# hyprlang noerror false
# You can make apps auto-start here
exec-once = /usr/lib/geoclue-2.0/demos/agent
exec-once = python3 /home/auysh/.config/hypr/custom/scripts/quote.py
exec-once = /home/auysh/.config/hypr/custom/scripts/slideshow.sh
# exec-once = sudo /usr/local/bin/location.sh # Requires passwordless sudo setup to work automatically
exec-once = /home/auysh/.config/hypr/custom/scripts/patcher.sh
# --- POPUP SCRIPTS ---
exec-once = ~/.config/hypr/custom/scripts/check_keys.sh
exec-once = ~/.config/hypr/custom/scripts/monitor_devices.py
exec-once = sleep 2 && echo "neutral|SYSTEM|Welcome Back" >> /tmp/qs_popup.log
# Silently refresh Quickshell after 5 seconds to fix Dock apps


exec-once = bash ~/.config/quickshell/scripts/autostart_triggers.sh