decoration {

    blur {
        enabled = true

        xray = false

        # Performance optimizations
        special = false
        new_optimizations = true

        # High quality blur settings
        size = 2
        passes = 2

        # Fixes for context menus/popups (CRITICAL)
        popups = true
        popups_ignorealpha = 0.5
        input_methods = true
        input_methods_ignorealpha = 0.5

        # Visual tuning
        brightness = 1

        noise = 0.03            # Adds subtle grain to prevent banding
        contrast = 1    # Slightly higher contrast for readability
        vibrancy = 0.5          # Boosts colors behind the blur
        vibrancy_darkness = 0.1
    }
}

misc {
    vrr = 1
}
