# Mic Mute Toggle
bind = , XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle && (wpctl get-volume @DEFAULT_AUDIO_SOURCE@ | grep -q MUTED && echo "bad|MIC|Muted" >> /tmp/qs_popup.log || echo "good|MIC|Unmuted" >> /tmp/qs_popup.log)

# App Drawer Keybind

# App Drawer Keybind
bind = SUPER, R, exec, qs -c ii ipc call "app-drawer" "toggle"

# System Monitor
bind = SUPER, Escape, exec, qs -c ii ipc call system-monitor toggle

# Sticky Notes


# Sticky Notes Layer
bind = SUPER SHIFT, N, exec, qs -c ii ipc call stickyNotes toggle

# Lyrics Layer
bind = SUPER SHIFT, Y, exec, qs -c ii ipc call lyrics toggle


bind = SUPER SHIFT, V, exec, qs -c ii ipc call lyrics fullscreen