# Remove upstream "disable blur everywhere" rule
windowrule = match:class .*, no_blur off
windowrule = match:class ^()$, match:title ^()$, no_blur off

# App Drawer blur rules
layerrule = match:namespace app-drawer, blur on
layerrule = match:namespace app-drawer, ignore_alpha 0.5

layerrule = match:namespace system-monitor, no_anim on
layerrule = match:namespace app-drawer, no_anim on
layerrule = match:namespace system-monitor, blur on
layerrule = match:namespace system-monitor, ignore_alpha 0.5
layerrule = match:namespace .*, xray 0

# Lyrics Layer
layerrule = match:namespace lyrics-layer, blur on
layerrule = match:namespace lyrics-layer, ignore_alpha 0.5

# Sticky Notes
layerrule = match:namespace stickynotes, blur on
layerrule = match:namespace stickynotes, ignore_alpha 0.5
layerrule = match:namespace stickynotes, no_anim on


