# Remove upstream "disable blur everywhere" rule
windowrule = match:class .*, no_blur off
windowrule = match:class ^()$, match:title ^()$, no_blur off

# App Drawer blur rules
layerrule = match:namespace app-drawer, blur on
layerrule = match:namespace app-drawer, ignore_alpha 0.5

layerrule = match:namespace system-monitor, no_anim on
layerrule = match:namespace app-drawer, no_anim on
layerrule = match:namespace system-monitor, blur on
layerrule = match:namespace system-monitor, ignore_alpha 0.5
layerrule = match:namespace .*, xray 0

# Lyrics Layer
layerrule = match:namespace lyrics-layer, blur on
layerrule = match:namespace lyrics-layer, ignore_alpha 0.5

# Notes Layer
layerrule = match:namespace quickshell:notes, blur on
layerrule = match:namespace quickshell:notes, ignore_alpha 0.5



layerrule = match:namespace kde-connect-drawer, blur on
layerrule = match:namespace kde-connect-drawer, ignore_alpha 0.5

# Phone Mirror (scrcpy) - floating window
windowrule = match:title PhoneMirror, float on
windowrule = match:title PhoneMirror, size 354 790
windowrule = match:title PhoneMirror, move 100%-420 100%-820

# Quickshell Popups
layerrule = match:namespace quickshell:popup, blur on
layerrule = match:namespace quickshell:popup, ignore_alpha 0.5

# windowrulev2 = blur, class:^(zen)$


# Ensure blur is enabled for Zen
# windowrule = match:class ^(zen)$, no_blur off
# Music Layer
layerrule = match:namespace music-layer, blur on
layerrule = match:namespace music-layer, ignore_alpha 0.5
